name: Rails CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Change this to match your Ruby version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set up database
        run: |
          bin/rails db:setup

      - name: Check for Rails app build issues
        run: |
          bin/rails db:migrate
          bin/rails server --environment=test
